const productsList = [

    {
        id: 1,
        title: 'Vela Barata',
        type: 1,
        description: 'Una de nuestras velas Económicas',
        description2: 'Se trata de un lote en formato ahorro y de calidad, ya que con solo una compra se adquiere una gran cantidad de velas. Son ideales para eventos especiales y salas grandes en las que se equiere contar con una gran cantidad d eiluminación y elementos decorativos ',
        price: 300,
        pictureUrl: "/candle1.jpg",

    },
    {
        id: 2,
        title: 'Vela aromática',
        type: 1,
        description: 'Vela arómatica sabor Canela',
        description2: 'Disfruta de la exótica y relajante experiencia que brinda esta vela perfumada, gracias a su aroma de la canela. Contiene ingredientes de calidad, que pueden llenar el ambiente del hogar de un aroma limpio y fresco. La mecha se ha fabricado con algodón de fibras naturales, además de encontrarse enderezada y centrada, para que arda de manera limpia y uniforme. Tiene una duración de 150 horas y genera una llama larga.',
        price: 500,
        pictureUrl: "/candle2.jpg",
    },

    {
        id: 3,
        title: 'Conjunto de Velas Blancas',
        type: 1,
        description: 'Set de 3 Velas ',
        description2: 'Conjunto de cinco velas blancas de uso hogareño con una duración larga e iluminación perfecta para toda ocasión',
        price: 400,
        pictureUrl: "/candle3.jpg",
    },
    {
        id: 4,
        title: 'Mini Velita',
        type: 1,
        description: 'Mini Velas para toda ocasión',
        description2: 'Pequeña vela de corta duración perfecta para momentos de disfrute con una bonita presentación',
        price: 100,
        pictureUrl: "/candle4.jpg",
    },
    {
        id: 5,
        title: 'Velas de Colores',
        type: 1,
        description: 'Velas multicolor para alegrar el día!',
        description2: 'Es el color de la espiritualidad, por eso las velas violetas son estupendas para meditar. ¡Además te ayudarán a desarrollar tu intuición! Según el Feng Shui, el violeta, el rojo y el naranja, juntos, representan la máxima prosperidad. ¡Así que ya sabes! ¿Qué te parece como regalo un paquete de estas tres velas para tus amigos?',
        price: 425,
        pictureUrl: "/candle5.jpg",
    },
    {
        id: 6,
        title: 'Set 2 candelbaros ',
        type: 2,
        description: 'Sin Velas',
        description2: 'Dos candelabros en diseños diferentes adecuado para una vela de pilcar cada uno. (Se entregan sin velas)',
        price: 700,
        pictureUrl: "/acc1.jpg",
    },
    {
        id: 7,
        title: '2 candelabros negros',
        type: 2,
        description: '60%Madera - 20%Vidrio - 20% Metal',
        description2: 'Dos candelabros en diseños diferentes adecuado para una vela de pilcar cada uno. (Se entregan sin velas)',
        price: 1300,
        pictureUrl: "/acc2.jpg",
    },
    {
        id: 8,
        title: '2 candelabros diseño moderno',
        type: 2,
        description: 'No incluye velas',
        description2: 'Dos candelabros en diseños diferentes adecuado para una vela de pilcar cada uno. (Se entregan sin velas)',
        price: 1000,
        pictureUrl: "/acc3.jpg",
    },
    {
        id: 9,
        title: '3 candelabros madera',
        type: 2,
        description: '85%Madera - 15% Metal',
        description2: 'Tres candelabros adecuado para una vela de pilcar cada uno. (Se entregan sin velas)',
        price: 1200,
        pictureUrl: "/acc4.jpg",
    },
    {
        id: 10,
        title: '3 candelabros basicos',
        type: 2,
        description: 'Candelabros básicos',
        description2: 'Tres candelabros en diseños basicos para una vela de pilcar cada uno. (Se entregan sin velas)',
        price: 600,
        pictureUrl: "/acc5.jpg",
    }]

export default productsList